// Embeds xterm.js and its fit addon into src/features/terminal/xterm.generated.ts, so the terminal page needs no
// network and no file assets (design §17). Run after upgrading @xterm/xterm or @xterm/addon-fit:
//   npx tsx scripts/build-terminal.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(__dirname, '..');
const pkg = (name: string) =>
  JSON.parse(readFileSync(join(root, 'node_modules', name, 'package.json'), 'utf8')) as { version: string };
const read = (path: string) => readFileSync(join(root, 'node_modules', path), 'utf8');
// Inside <script>, a literal "</script" would end the element early.
const script = (code: string) => code.replace(/<\/script/gi, '<\\/script');

const xterm = pkg('@xterm/xterm').version;
const fit = pkg('@xterm/addon-fit').version;
const out = `// Generated by scripts/build-terminal.ts from @xterm/xterm ${xterm} and @xterm/addon-fit ${fit}. Do not edit.
// xterm.js and its addons: Copyright (c) 2017-2025 The xterm.js authors, MIT License
// (https://github.com/xtermjs/xterm.js/blob/master/LICENSE).
/* eslint-disable */
export const XTERM_VERSION = ${JSON.stringify(xterm)};
export const FIT_VERSION = ${JSON.stringify(fit)};
export const XTERM_CSS = ${JSON.stringify(read('@xterm/xterm/css/xterm.css'))};
export const XTERM_JS = ${JSON.stringify(script(read('@xterm/xterm/lib/xterm.js')))};
export const FIT_JS = ${JSON.stringify(script(read('@xterm/addon-fit/lib/addon-fit.js')))};
`;
const target = join(root, 'src/features/terminal/xterm.generated.ts');
writeFileSync(target, out);
console.log(`${target}: ${Math.round(out.length / 1024)} KB`);
